---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - name: web
    port: 9090
    nodePort: 30091
    protocol: TCP
  selector:
    prometheus: prometheus
  type: NodePort
