---
  - name: Install Docker Dependencies
    package:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
 
  - name: echo
    command:
      argv:
        - echo
        - "{{ansible_distribution}}"
 
  - name: Add GPG keys for Ubuntu distribution
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    when: "ansible_distribution == 'Ubuntu'"

  - name: Add docker repository for ubuntu 
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
    when: "ansible_distribution == 'Ubuntu'"

  - name: Install Docker Engine if not present
    package:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      -  docker-ce-cli
      - containerd.io
      
  - name: Enable and Start Docker as system service
    service:
      name: docker
      state: started
      enabled: yes


