---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30080 
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      nodePort: 30083
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
