---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: grafana
spec:
  type: NodePort
  ports:
  - name: service
    port: 3000
    protocol: TCP
    nodePort: 30092
  selector:
    app: grafana
